# Generated by Django 2.1.5 on 2019-01-31 12:24

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('date_of_birth', models.DateField(max_length=128)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=128)),
                ('date_of_joining', models.DateField(max_length=128)),
                ('email', models.EmailField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('phone_no', models.CharField(max_length=128, unique=True)),
                ('address', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=128)),
                ('qualification', models.CharField(max_length=128)),
                ('designation', models.CharField(max_length=128)),
                ('skills', models.CharField(max_length=128)),
                ('experience', models.IntegerField()),
                ('dept', models.ForeignKey(on_delete=builtins.id, to='employee.department')),
            ],
        ),
    ]
