# Generated by Django 2.1.5 on 2019-02-01 04:30

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_reason', models.CharField(max_length=128)),
                ('leave_date', models.DateField()),
                ('dept', models.ForeignKey(on_delete=builtins.id, to='employee.department')),
            ],
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=128)),
                ('project_start_date', models.DateField()),
                ('project_end_date', models.DateField()),
                ('project_technology', models.CharField(max_length=128)),
                ('dept', models.ForeignKey(on_delete=builtins.id, to='employee.department')),
            ],
        ),
        migrations.CreateModel(
            name='salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_salary', models.IntegerField()),
                ('dept', models.ForeignKey(on_delete=builtins.id, to='employee.department')),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_joining',
            field=models.DateField(),
        ),
        migrations.AddField(
            model_name='salary',
            name='emp',
            field=models.ForeignKey(on_delete=builtins.id, to='employee.employee'),
        ),
        migrations.AddField(
            model_name='project',
            name='emp',
            field=models.ForeignKey(on_delete=builtins.id, to='employee.employee'),
        ),
        migrations.AddField(
            model_name='leave',
            name='emp',
            field=models.ForeignKey(on_delete=builtins.id, to='employee.employee'),
        ),
    ]
