# Generated by Django 2.1.5 on 2019-02-01 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20190201_0430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary',
            name='dept',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='emp',
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name_plural': 'Department'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name_plural': 'Employee'},
        ),
        migrations.AlterModelOptions(
            name='leave',
            options={'verbose_name_plural': 'Leave'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name_plural': 'Project'},
        ),
        migrations.AddField(
            model_name='employee',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='profile_images'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='leave_date',
            field=models.DateField(blank=True, default=0),
        ),
        migrations.DeleteModel(
            name='salary',
        ),
    ]
