# Generated by Django 2.1.5 on 2019-02-01 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_employee_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.department'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.department'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='emp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee'),
        ),
        migrations.AlterField(
            model_name='project',
            name='dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.department'),
        ),
        migrations.AlterField(
            model_name='project',
            name='emp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee'),
        ),
    ]
