# Generated by Django 2.1.5 on 2019-02-05 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_auto_20190201_1158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='dept_name',
            new_name='dname',
        ),
    ]
