# Generated by Django 2.1.5 on 2019-02-05 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_auto_20190205_0933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='dname',
            new_name='dept_name',
        ),
    ]
